--- 
- hosts: localhost
  become: true
  roles:
    - instance

- name: Install Tomcat & Deploy files
  hosts: ec2hosts
  gather_facts: False
  user: root
  become: yes
  become_method: sudo

  vars_files:
    - ./group_vars/variable
         
  roles:
    - selinux
    - tomcatinstall

